export const BANDERAS: Record<string, string> = {
    "Australia": "AU",
    "Canadá": "CA",
    "Costa Rica": "CR",
    "Croacia": "HR",
    "Egipto": "EG",
    "España": "ES",
    "Estados Unidos": "US",
    "EEUU": "US",
    "Francia": "FR",
    "Japón": "JP",
    "Corea del Sur": "KR",
    "Marruecos": "MA",
    "México": "MX",
    "Nueva Zelanda": "NZ",
    "Nigeria": "NG",
    "Países Bajos": "NL",
    "Portugal": "PT",
    "Senegal": "SN",
    "Suiza": "CH",
    "Túnez": "TN",

    // UEFA
    "Alemania": "DE",
    "Inglaterra": "GB",
    "Italia": "IT",
    "Bélgica": "BE",
    "Dinamarca": "DK",
    "Noruega": "NO",
    "Suecia": "SE",
    "Polonia": "PL",
    "Serbia": "RS",
    "Turquía": "TR",
    "Ucrania": "UA",
    "Austria": "AT",
    "República Checa": "CZ",
    "Grecia": "GR",
    "Escocia": "GB",
    "Gales": "GB",
    "Rumania": "RO",
    "Hungría": "HU",
    "Eslovaquia": "SK",
    "Eslovenia": "SI",
    "Bosnia-Herzegovina": "BA",
    "Bosnia y Herzegovina": "BA",

    // CONMEBOL
    "Argentina": "AR",
    "Brasil": "BR",
    "Ecuador": "EC",
    "Colombia": "CO",
    "Paraguay": "PY",
    "Uruguay": "UY",

    // AFC
    "Irán": "IR",
    "Arabia Saudita": "SA",
    "Qatar": "QA",
    "Emiratos Árabes Unidos": "AE",
    "Irak": "IQ",
    "Uzbekistán": "UZ",
    "Jordania": "JO",
    "Omán": "OM",
    "China": "CN",

    // CAF
    "Argelia": "DZ",
    "Camerún": "CM",
    "Costa de Marfil": "CI",
    "Ghana": "GH",
    "Mali": "ML",
    "Burkina Faso": "BF",
    "República Democrática del Congo": "CD",
    "Sudáfrica": "ZA",
    "Cabo Verde": "CV",

    // CONCACAF
    "Panamá": "PA",
    "Honduras": "HN",
    "Jamaica": "JM",
    "El Salvador": "SV",
    "Guatemala": "GT",
    "Trinidad y Tobago": "TT",

    // OFC
    "Islas Salomón": "SB",
    "Nueva Caledonia": "NC",

};